server:
  # 端口
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
    #连接池
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10 #最大连接数，默认10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#Mybatis plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置Mybatis数据返回类型别名（默认是类名）
  type-aliases-package: com.cc.pojo
  configuration:
    #自动驼峰命名
    map-underscore-to-camel-case: false
#Mybatis SQL 打印（方法接口所在的包，不是Mapper.xml所在的包）
#logging:
#  level:
#    com:
#      cc:
#        mapper: debug
jwt:
  # JWT 存储的请求头
  tokenHeader: Authorization
  #JWT 加解密使用的密钥
  secret: yeb-secret
  #JWT的超载期限时间（60*60*24）
  expiration: 604880
  #JWT 负载中拿到开头
  tokenHead: Bearer

